### PR TITLE
Updating from v6.0.0 to v7.4.0

### PR DESCRIPTION
**Pull request by ThomasOrtiz**
[PUBG Changelog](https://documentation.pubg.com/en/changelog/changelog.html)

## v6.0.0
* Fixed bug related to `bestRankPoint` being spelling as `bestRankPoints`

## v7.0.0
* Added `xbox-sa` as a valid region
* Added a `status` api in order to get the status of the api and its ping/heartbeat.

## v7.1.0
* Added `LogPlayerAttack.fireWeaponStackCount`

## v7.4.0
* Added `LogPlayerPosition.vehicle`

## Misc
* Added `XBOX` as a **PlatformRegion** since endpoints from now on will support it.
* Added `PSN` and `psn-{region}` to the **PlatformRegion** enum

### CODE REVIEW

**Comment by ThomasOrtiz** [comment]
@martinsileno I went ahead and updated this library to be compatible with v7.4.0 of PUBG's api.

I've added changes, relevant tests, and ensured that the project is error free and passes all tests,

**Comment by ThomasOrtiz** [comment]
@martinsileno Is there any update on this?

**Comment by martinsileno** [comment]
Hi @Tdortiz, sorry for the delay. 

I'm on vacation at the moment, so I don't have much time and can't release new versions on NPM until the 24th of November.

Let me know if this is ok to close, I quickly looked at the changes and it seems OK!

**Comment by ThomasOrtiz** [comment]
@martinsileno No problem! Enjoy your vacation :) 

I've been running my Discord Bot with these changes locally for a few days and everything is working as expected. I think it should be good to close 👍

**Comment by ThomasOrtiz** [comment]
@martinsileno I went ahead and added support for Playstation

**Comment by martinsileno** [comment]
Merged and released as 1.6.0, thanks!

**Comment by EngMarko110** [comment]
please, anyone know the topic or video explaining how I can use this (pubg document), please?
i use node js and typescript not professional 
Thanks

**Pull request merged**
